name: Check Built ISO

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - name: Download gamma-lite artifact
        uses: actions/download-artifact@v4
        with:
          name: gamma-lite
          path: output
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 29739836293

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso squashfs-tools

      - name: Check ISO
        run: |
          ls -lh output/

          xorriso \
            -indev output/gamma-lite.iso \
            -ls /

      - name: Extract ISO
        run: |
          mkdir iso-root

          xorriso \
            -osirrox on \
            -indev output/gamma-lite.iso \
            -extract / iso-root

          ls -lh iso-root/casper

      - name: Check SquashFS
        run: |
          sudo mkdir -p /mnt/gamma

          sudo mount \
            -o loop,ro \
            iso-root/casper/filesystem.squashfs \
            /mnt/gamma

          echo "===== INIT ====="
          ls -l /mnt/gamma/sbin/init

          echo "===== SYSTEMD ====="
          ls -l /mnt/gamma/lib/systemd/systemd

          echo "===== OS ====="
          cat /mnt/gamma/etc/os-release
