name: Upload to v2.1-Royal

on:
  push:
    tags:
      - 'v2.1-Royal' # يخدم غير مع هذا التاغ

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev fakeroot

      - name: Build DEB v2.1-Royal
        run: |
          VER="2.1-Royal"

          mkdir -p gamma-store-pro_$VER/DEBIAN
          mkdir -p gamma-store-pro_$VER/usr/bin
          mkdir -p gamma-store-pro_$VER/usr/share/applications
          mkdir -p gamma-store-pro_$VER/usr/share/pixmaps

          cp gamma-store.sh gamma-store-pro_$VER/usr/bin/gamma-store
          chmod 755 gamma-store-pro_$VER/usr/bin/gamma-store
          cp assets/F-logo.png gamma-store-pro_$VER/usr/share/pixmaps/

          cat > gamma-store-pro_$VER/usr/share/applications/gamma-store.desktop <<EOF
          [Desktop Entry]
          Name=Gamma Store Pro Royal
          Exec=gamma-store
          Icon=F-logo
          Type=Application
          Categories=Utility;
          EOF

          cat > gamma-store-pro_$VER/DEBIAN/control <<EOF
          Package: gamma-store-pro
          Version: 2.1-Royal
          Section: utils
          Priority: optional
          Architecture: all
          Depends: yad, termux-x11-nightly
          Maintainer: Taki <taki@gammalinex.dev>
          Description: Gamma Store Pro v2.1-Royal
           Play Store Clone. Special Dedication to Fateh ∞
          EOF

          dpkg-deb --build gamma-store-pro_$VER
          mv gamma-store-pro_$VER.deb gamma-store-pro_2.1-Royal_all.deb

      - name: Upload to v2.1-Royal Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.1-Royal # يلحق هنا بالضبط
          files: gamma-store-pro_2.1-Royal_all.deb
          overwrite: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
